//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Detail_Order = new HashSet<Detail_Order>();
        }
    
        public int ID_Product { get; set; }
        public Nullable<int> ID_Category { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<int> ID_Size { get; set; }
        public Nullable<int> ID_Material { get; set; }
        public Nullable<int> ID_Warranty { get; set; }

        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail_Order> Detail_Order { get; set; }
        public virtual Material Material { get; set; }
        public virtual Size Size { get; set; }
        public virtual Warranty_Policy Warranty_Policy { get; set; }
    }
}
