//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KidMartStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chi_tiết_đơn_hàng
    {
        public int Mã_chi_tiết_đơn_hàng { get; set; }
        public int Mã_đơn_hàng { get; set; }
        public int Mã_sản_phẩm { get; set; }
        public int Số_lượng { get; set; }
        public decimal Đơn_giá { get; set; }
    
        public virtual Đơn_hàng Đơn_hàng { get; set; }
        public virtual Sản_phẩm Sản_phẩm { get; set; }
    }
}
