//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KidMartStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
<<<<<<< HEAD
            this.Carts = new HashSet<Cart>();
=======
>>>>>>> Laptop-My
            this.Orders = new HashSet<Order>();
        }
    
        public int ID_Customer { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
<<<<<<< HEAD
        public string Password { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
=======
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public string Password { get; set; }
>>>>>>> Laptop-My
        public string Avatar { get; set; }
        public string Role { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
<<<<<<< HEAD
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
=======
>>>>>>> Laptop-My
        public virtual ICollection<Order> Orders { get; set; }
    }
}
