//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KidMartStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail_Order
    {
        public int ID_Detail_Order { get; set; }
        public int ID_Order { get; set; }
        public int ID_Product { get; set; }
        public int Quantity { get; set; }
        public decimal Unit_Price { get; set; }

        public virtual Order Order { get; set; }
    }
}
