//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KidMartStore.Models
{
    using System;
    using System.Collections.Generic;
    
<<<<<<<< HEAD:KidMartStore/KidMartStore/Models/Detail_Cart.cs
    public partial class Detail_Cart
    {
        public int ID_Detail_Cart { get; set; }
        public int ID_Cart { get; set; }
        public int ID_Product { get; set; }
        public int Quantity { get; set; }
    
        public virtual Cart Cart { get; set; }
========
    public partial class Detail_Order
    {
        public int ID_Detail_Order { get; set; }
        public int ID_Order { get; set; }
        public int ID_Product { get; set; }
        public int Quantity { get; set; }
        public decimal Unit_Price { get; set; }

        public virtual Order Order { get; set; }
>>>>>>>> Laptop-My:KidMartStore/KidMartStore/Models/Detail_Order.cs
    }
}
