//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KidMartStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giỏ_hàng
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Giỏ_hàng()
        {
            this.Chi_tiết_giỏ_hàng = new HashSet<Chi_tiết_giỏ_hàng>();
        }
    
        public int Mã_giỏ_hàng { get; set; }
        public int Mã_KH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chi_tiết_giỏ_hàng> Chi_tiết_giỏ_hàng { get; set; }
        public virtual Khách_Hàng Khách_Hàng { get; set; }
    }
}
