//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KidMartStore.Models
{
    using System;
    using System.Collections.Generic;
    
<<<<<<<< HEAD:KidMartStore/KidMartStore/Models/Category.cs
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
========
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
>>>>>>>> Laptop-My:KidMartStore/KidMartStore/Models/Material.cs
        {
            this.Products = new HashSet<Product>();
        }
    
<<<<<<<< HEAD:KidMartStore/KidMartStore/Models/Category.cs
        public int ID_Category { get; set; }
        public string Name_Category { get; set; }
========
        public int ID_Material { get; set; }
        public string Name_Material { get; set; }
>>>>>>>> Laptop-My:KidMartStore/KidMartStore/Models/Material.cs
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
