//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KidMartStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sản_phẩm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sản_phẩm()
        {
            this.Chi_tiết_đơn_hàng = new HashSet<Chi_tiết_đơn_hàng>();
            this.Chi_tiết_giỏ_hàng = new HashSet<Chi_tiết_giỏ_hàng>();
        }
    
        public int Mã_sản_phẩm { get; set; }
        public int Mã_danh_mục { get; set; }
        public string Tên_sản_phẩm { get; set; }
        public decimal Giá_bán { get; set; }
        public int Số_lượng_tồn_kho { get; set; }
        public string Mô_tả { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chi_tiết_đơn_hàng> Chi_tiết_đơn_hàng { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chi_tiết_giỏ_hàng> Chi_tiết_giỏ_hàng { get; set; }
        public virtual Danh_mục_sản_phẩm Danh_mục_sản_phẩm { get; set; }
    }
}
