//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KidMartStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Đơn_hàng
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Đơn_hàng()
        {
            this.Chi_tiết_đơn_hàng = new HashSet<Chi_tiết_đơn_hàng>();
        }
    
        public int Mã_đơn_hàng { get; set; }
        public int Mã_KH { get; set; }
        public System.DateTime Ngày_đặt_hàng { get; set; }
        public decimal Tổng_tiền { get; set; }
        public string Trạng_thái { get; set; }
        public Nullable<int> Mã_giảm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chi_tiết_đơn_hàng> Chi_tiết_đơn_hàng { get; set; }
        public virtual Giảm_giá Giảm_giá { get; set; }
        public virtual Khách_Hàng Khách_Hàng { get; set; }
    }
}
